if not morescience.tech then morescience.tech = {} end

--for dealing with dynamic recipes generated by Omni, use 
--omnitech-more-science-pack-i-level
--if data.raw.technology["omnitech-more-science-pack-18-1"] then
--morescience.tech.add_science_pack_range({"omnitech-more-science-pack-18-1"}, 1, 12, 1)
--if errors that pack is already registered, then it must be done in data-final-fixes 


if not settings.startup["moresciencepack-GameProgressionFix"].value == true then 

	--unable to reference within data-final-fixes.
	local blacklist = 
	{
		--"military-2",
	}
	--conditional mod & config dependent setting application, use from template below: 
	--if mods["boblogistics"] and settings.startup["bobmods-logistics-inserteroverhaul"].value == true then

	--Technology Pre-requisite fixes use: morescience.tech.remove_prerequisite(technology, prerequisite)
	if mods["aai-industry"] then
	morescience.tech.remove_prerequisite("turrets", "military") --fix technology override that breaks progression if AAI Industry is added. 
	end


end