data:extend(
{
  {
    type = "tool",
    name = "more-science-pack-1",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-1.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-01]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-2",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-2.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-02]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-3",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-3.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-03]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-4",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-4.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-04]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-5",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-5.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-05]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-6",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-6.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-06]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-7",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-7.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-07]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-8",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-8.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-08]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-9",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-9.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-09]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-10",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-10.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-10]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-11",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-11.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-11]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-12",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-12.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-12]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-13",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-13.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-13]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-14",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-14.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-14]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-15",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-15.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-15]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-16",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-16.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-16]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-17",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-17.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-17]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-18",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-18.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-18]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-19",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-19.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-19]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-20",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-20.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-20]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-21",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-21.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-21]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-22",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-22.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-22]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-23",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-23.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-23]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-24",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-24.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-24]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-25",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-25.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-25]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-26",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-26.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-26]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-27",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-27.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-27]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-28",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-28.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-28]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-29",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-29.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-29]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
  {
    type = "tool",
    name = "more-science-pack-30",
    localised_description = {"item-description.science-pack"},
    icon = "__MoreSciencePacks-for1_1__/graphics/icons/more-science-pack-30.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "z[zmore-science-pack-30]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value"
  },
}
)